In [36]:
import numpy as np
import pandas as pd

import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn

In [37]:
df_white = pd.read_csv('C:\\Users\\Admin\\winequality-white.csv',encoding='cp1251', sep=';')
df_white.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  quality  
0      8.8        6  
1      9.5        6  
2     10.1        6  
3      9.9        6  
4      9.9        6

In [38]:
df_white.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    4898.000000       4898.000000  4898.000000     4898.000000   
mean        6.854788          0.278241     0.334192        6.391415   
std         0.843868          0.100795     0.121020        5.072058   
min         3.800000          0.080000     0.000000        0.600000   
25%         6.300000          0.210000     0.270000        1.700000   
50%         6.800000          0.260000     0.320000        5.200000   
75%         7.300000          0.320000     0.390000        9.900000   
max        14.200000          1.100000     1.660000       65.800000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  4898.000000          4898.000000           4898.000000  4898.000000   
mean      0.045772            35.308085            138.360657     0.994027   
std       0.021848            17.007137             42.498065     0.002991   
min       0.009000             2.000000              9.000000     0.987110   
25%       0.036000            23.000000            108.000000     0.991723   
50%       0.043000            34.000000            134.000000     0.993740   
75%       0.050000            46.000000            167.000000     0.996100   
max       0.346000           289.000000            440.000000     1.038980   

                pH    sulphates      alcohol      quality  
count  4898.000000  4898.000000  4898.000000  4898.000000  
mean      3.188267     0.489847    10.514267     5.877909  
std       0.151001     0.114126     1.230621     0.885639  
min       2.720000     0.220000     8.000000     3.000000  
25%       3.090000     0.410000     9.500000     5.000000  
50%       3.180000     0.470000    10.400000     6.000000  
75%       3.280000     0.550000    11.400000     6.000000  
max       3.820000     1.080000    14.200000     9.000000

In [39]:
from collections import Counter
Counter(df_white['quality'])

Counter({6: 2198, 5: 1457, 7: 880, 8: 175, 4: 163, 3: 20, 9: 5})

In [40]:
Quality = df_white['quality'].values
category = []
for num in Quality:
    if num<5:
        category.append('Bad')
    elif num>6:
        category.append('Excellent')
    else:
        category.append('Good')

In [41]:
category = pd.DataFrame(data=category, columns=['category'])
data = pd.concat([df_white,category],axis=1)
data.drop(columns='quality',axis=1,inplace=True)
data.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol category  
0      8.8     Good  
1      9.5     Good  
2     10.1     Good  
3      9.9     Good  
4      9.9     Good

In [42]:
data['category'].value_counts()

Good         3655
Excellent    1060
Bad           183
Name: category, dtype: int64

In [43]:
x = data.iloc[:,:11]  # rest are features
y = data['category']  # set 'category' as target

In [44]:
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.0              0.27         0.36            20.7      0.045   
1            6.3              0.30         0.34             1.6      0.049   
2            8.1              0.28         0.40             6.9      0.050   
3            7.2              0.23         0.32             8.5      0.058   
4            7.2              0.23         0.32             8.5      0.058   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 45.0                 170.0   1.0010  3.00       0.45   
1                 14.0                 132.0   0.9940  3.30       0.49   
2                 30.0                  97.0   0.9951  3.26       0.44   
3                 47.0                 186.0   0.9956  3.19       0.40   
4                 47.0                 186.0   0.9956  3.19       0.40   

   alcohol  
0      8.8  
1      9.5  
2     10.1  
3      9.9  
4      9.9

In [45]:
y.head()

0    Good
1    Good
2    Good
3    Good
4    Good
Name: category, dtype: object

In [125]:
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.25)

Linear Regression

In [132]:
x1=df_white.drop('quality',axis=1)
y1=df_white['quality']

from sklearn.linear_model import LinearRegression
x1_train, x1_test, y1_train, y1_test = train_test_split(x1, y1, test_size = 0.25)

lr=LinearRegression()
lr.fit(x1_train,y1_train)
lr_predict =lr.predict(x1_test)
print('R^2 = ',format(lr.score(x1,y1)))    #линейная регрессия не перспективна

R^2 =  0.2811114394657578


SVM

In [126]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train,y_train)              #обучение
svc_predict =svc.predict(x_test)      #предсказание


C:\Users\Admin\Anaconda3\lib\site-packages\sklearn\svm\base.py:193: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [74]:
svc_conf_matrix = confusion_matrix(y_test, svc_predict)
svc_acc_score = accuracy_score(y_test, svc_predict)
print(svc_conf_matrix)
print(svc_acc_score*100)

[[  1   0  46]
 [  0  87 167]
 [  1  46 877]]
78.77551020408163


In [75]:
for i in range(0,5):
    print('Actual wine quality is ', y_test.iloc[i], ' and predicted is ', svc_predict[i])

Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Excellent  and predicted is  Good


Random Forest

In [95]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)        
rf_predict=rf.predict(x_test)   

In [96]:
rf_conf_matrix = confusion_matrix(y_test, rf_predict)
rf_acc_score = accuracy_score(y_test, rf_predict)
print(rf_conf_matrix)
print(rf_acc_score*100)

[[  7   1  39]
 [  0 156  98]
 [  5  40 879]]
85.06122448979592


In [97]:
for i in range(0,5):
    print('Actual wine quality is ', y_test.iloc[i], ' and predicted is ', rf_predict[i])

Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Excellent  and predicted is  Good


Gaussian Naive Bayes

In [64]:
from sklearn.naive_bayes import GaussianNB
nb = GaussianNB()
nb.fit(x_train,y_train)
nb_predict=nb.predict(x_test)

In [65]:
nb_conf_matrix = confusion_matrix(y_test, nb_predict)
nb_acc_score = accuracy_score(y_test, nb_predict)
print(nb_conf_matrix)
print(nb_acc_score*100)

[[ 14   4  29]
 [  1 175  78]
 [ 22 248 654]]
68.81632653061224


In [71]:
for i in range(0,5):
    print('Actual wine quality is ', y_test.iloc[i], ' and predicted is ', nb_predict[i])

Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Excellent
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Excellent
Actual wine quality is  Excellent  and predicted is  Excellent


Gradient Boosting Classifier

In [122]:
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(n_estimators=150)
gb.fit(x_train, y_train)        
gb_predict=gb.predict(x_test) 

In [123]:
gb_conf_matrix = confusion_matrix(y_test, gb_predict)
gb_acc_score = accuracy_score(y_test, gb_predict)
print(gb_conf_matrix)
print(gb_acc_score*100)

[[ 10   0  37]
 [  0 121 133]
 [ 17  54 853]]
80.3265306122449


In [124]:
for i in range(0,5):
    print('Actual wine quality is ', y_test.iloc[i], ' and predicted is ', gb_predict[i])

Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Good  and predicted is  Good
Actual wine quality is  Excellent  and predicted is  Good
